<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\Company;
use App\Domain\Repository\CompanyRepository;
use App\Domain\Repository\UserRepository;
use App\Infrastructure\Dao\Generated\AbstractCompanyDao;
use App\Infrastructure\Logging\ModelLogger;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use TheCodingMachine\TDBM\ResultIterator;
use TheCodingMachine\TDBM\TDBMService;

/**
 * The CompanyDao class will maintain the persistence of Company class into the companies table.
 */
class CompanyDao extends AbstractCompanyDao implements CompanyRepository
{
    use ModelLogger;

    private TokenStorageInterface $tokenStorage;
    private UserRepository $userRepository;

    public const SORT_COLUMNS = [
        'name' => 'companies.name',
        'createdAt' => 'companies.created_at',
    ];

    public function __construct(TDBMService $tdbmService, TokenStorageInterface $tokenStorage, UserRepository $userRepository)
    {
        $this->tokenStorage = $tokenStorage;
        $this->userRepository = $userRepository;
        parent::__construct($tdbmService);
    }

    public function save(Company $company): void
    {
        $this->log($company);
        parent::save($company);
    }

    /**
     * @throws NotFound
     */
    public function mustFindOneById(string $id): Company
    {
        $company = $this->findOne(['id' => $id]);
        if ($company === null) {
            throw new NotFound(Company::class, ['id' => $id]);
        }

        return $company;
    }

    public function findOneByCode(string $code): ?Company
    {
        return $this->findOne('code = :code', ['code' => $code]);
    }

    public function findOneByName(string $name): ?Company
    {
        return $this->findOne('name = :name', ['name' => $name]);
    }

    protected function getTokenStorage(): TokenStorageInterface
    {
        return $this->tokenStorage;
    }

    protected function getUserRepository(): UserRepository
    {
        return $this->userRepository;
    }

    public function findByFilters(?string $search, ?string $sortColumn = null, ?string $sortDirection = 'asc'): ResultIterator
    {
        $filters = ['deleted = 0'];
        $parameters = [];
        if (! empty($search)) {
            $filters[] = 'name LIKE :search OR code LIKE :search';
            $parameters['search'] = '%' . $search . '%';
        }

        $orderBy = 'name ASC';
        if (! empty($sortColumn) && isset(self::SORT_COLUMNS[$sortColumn])) {
            $orderBy = self::SORT_COLUMNS[$sortColumn] . ' ' . ($sortDirection === 'asc' ? 'ASC' : 'DESC');
        }

        return $this->find($filters, $parameters, $orderBy);
    }
}
