<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\Event;
use App\Domain\Repository\EventRepository;
use App\Domain\Repository\UserRepository;
use App\Infrastructure\Dao\Generated\AbstractEventDao;
use App\Infrastructure\Logging\ModelLogger;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use TheCodingMachine\TDBM\ResultIterator;
use TheCodingMachine\TDBM\TDBMService;

/**
 * The EventDao class will maintain the persistence of Event class into the events table.
 */
class EventDao extends AbstractEventDao implements EventRepository
{
    use ModelLogger;

    public const SORT_COLUMNS = [
        'name' => 'name',
        'description' => 'description',
        'type' => 'type',
        'dateEvent' => 'date_event',
        'updatedAt' => 'updated_at',
        'status' => 'status',
    ];
    private TokenStorageInterface $tokenStorage;
    private UserRepository $userRepository;

    public function __construct(TDBMService $tdbmService, TokenStorageInterface $tokenStorage, UserRepository $userRepository)
    {
        $this->tokenStorage = $tokenStorage;
        $this->userRepository = $userRepository;
        parent::__construct($tdbmService);
    }

    public function save(Event $event): void
    {
        $this->log($event);
        parent::save($event);
    }

    /**
     * @throws NotFound
     */
    public function mustFindOneById(string $id): Event
    {
        $event = $this->findOne(['id' => $id]);
        if ($event === null) {
            throw new NotFound(Event::class, ['id' => $id]);
        }

        return $event;
    }

    protected function getTokenStorage(): TokenStorageInterface
    {
        return $this->tokenStorage;
    }

    protected function getUserRepository(): UserRepository
    {
        return $this->userRepository;
    }

    public function findByFilters(?string $search, ?string $status, string $sortColumn = 'createdAt', string $sortDirection = 'desc'): ResultIterator
    {
        $filters = [];
        $parameters = [];

        if (! empty($search)) {
            $filters[] = 'name LIKE :search OR description LIKE :search OR type LIKE :search';
            $parameters['search'] = '%' . $search . '%';
        }

        if (! empty($status)) {
            $filters[] = 'status = :status';
            $parameters['status'] = $status;
        }

        $orderBy = '';
        if (isset(self::SORT_COLUMNS[$sortColumn])) {
            $orderBy = self::SORT_COLUMNS[$sortColumn] . ' ' . ($sortDirection === 'desc' ? 'DESC' : 'ASC');
        }

        return $this->find($filters, $parameters, $orderBy);
    }
}
