<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\FileDescriptor;
use App\Domain\Repository\FileDescriptorRepository;
use App\Domain\Repository\UserRepository;
use App\Infrastructure\Dao\Generated\AbstractFileDescriptorDao;
use App\Infrastructure\Logging\ModelLogger;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use TheCodingMachine\TDBM\TDBMService;

/**
 * The FileDescriptorDao class will maintain the persistence of FileDescriptor class into the file_descriptors table.
 */
class FileDescriptorDao extends AbstractFileDescriptorDao implements FileDescriptorRepository
{
    use ModelLogger;

    private TokenStorageInterface $tokenStorage;
    private UserRepository $userRepository;

    public function __construct(TDBMService $tdbmService, TokenStorageInterface $tokenStorage, UserRepository $userRepository)
    {
        $this->tokenStorage = $tokenStorage;
        $this->userRepository = $userRepository;
        parent::__construct($tdbmService);
    }

    public function save(FileDescriptor $fileDescriptor): void
    {
        $this->log($fileDescriptor);
        parent::save($fileDescriptor);
    }

    /**
     * @throws NotFound
     */
    public function mustFindOneById(string $id): FileDescriptor
    {
        $fileDescriptor = $this->findOne(['id' => $id]);
        if ($fileDescriptor === null) {
            throw new NotFound(FileDescriptor::class, ['id' => $id]);
        }

        return $fileDescriptor;
    }

    protected function getTokenStorage(): TokenStorageInterface
    {
        return $this->tokenStorage;
    }

    protected function getUserRepository(): UserRepository
    {
        return $this->userRepository;
    }
}
