<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\ProgramModel;
use App\Domain\Repository\ProgramModelRepository;
use App\Domain\Repository\UserRepository;
use App\Infrastructure\Dao\Generated\AbstractProgramModelDao;
use App\Infrastructure\Logging\ModelLogger;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use TheCodingMachine\TDBM\ResultIterator;
use TheCodingMachine\TDBM\TDBMService;

/**
 * The ProgramModelDao class will maintain the persistence of ProgramModel class into the program_models table.
 */
class ProgramModelDao extends AbstractProgramModelDao implements ProgramModelRepository
{
    use ModelLogger;

    public const SORT_COLUMNS = [
        'name' => 'name',
        'createdAt' => 'created_at',
        'description' => 'description',
    ];

    private TokenStorageInterface $tokenStorage;
    private UserRepository $userRepository;

    public function __construct(TDBMService $tdbmService, TokenStorageInterface $tokenStorage, UserRepository $userRepository)
    {
        $this->tokenStorage = $tokenStorage;
        $this->userRepository = $userRepository;
        parent::__construct($tdbmService);
    }

    protected function getTokenStorage(): TokenStorageInterface
    {
        return $this->tokenStorage;
    }

    protected function getUserRepository(): UserRepository
    {
        return $this->userRepository;
    }

    public function save(ProgramModel $programModel): void
    {
        $this->log($programModel);
        parent::save($programModel);
    }

    public function mustFindOneById(string $id): ProgramModel
    {
        $event = $this->findOne(['id' => $id]);
        if ($event === null) {
            throw new NotFound(ProgramModel::class, ['id' => $id]);
        }

        return $event;
    }

    public function findByFilters(?string $search, ?string $sortColumn = 'createdAt', ?string $sortDirection = 'desc'): ResultIterator
    {
        $parameters = [];
        $filters = ['deleted = 0'];
        if (! empty($search)) {
            $filters[] = 'name LIKE :search OR description LIKE :search';
            $parameters['search'] = '%' . $search . '%';
        }

        $orderBy = '';
        if (isset(self::SORT_COLUMNS[$sortColumn])) {
            $orderBy = self::SORT_COLUMNS[$sortColumn] . ' ' . ($sortDirection === 'desc' ? 'DESC' : 'ASC');
        }

        return $this->find($filters, $parameters, $orderBy);
    }
}
