<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Exception\NotFound;
use App\Domain\Model\UserType;
use App\Domain\Repository\UserTypeRepository;
use App\Infrastructure\Dao\Generated\AbstractUserTypeDao;

/**
 * The UserTypeDao class will maintain the persistence of UserType class into the users_types table.
 */
class UserTypeDao extends AbstractUserTypeDao implements UserTypeRepository
{
    /**
     * @throws NotFound
     */
    public function mustFindOneById(string $id): UserType
    {
        $userType = $this->findOne(['id' => $id]);
        if ($userType === null) {
            throw new NotFound(UserType::class, ['id' => $id]);
        }

        return $userType;
    }
}
