version: '3.7'

services:

  traefik:
    image: traefik:2.0
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    image: thecodingmachine/nodejs:12-apache
    labels:
      - traefik.enable=true
      - traefik.http.routers.extranet_router.rule=Host(`${HOST_URL}`)
    environment:
      # Docker image
      STARTUP_COMMAND_0: "npm install"
      STARTUP_COMMAND_1: "npm run build"
      # Apollo
      VUE_APP_GRAPHQL_HTTP: "http://api.$HOST_URL/graphql"
      # Apache
      APACHE_DOCUMENT_ROOT: "dist/"
    volumes:
      - ./src/webapp:/var/www/html:rw

  api:
    image: thecodingmachine/php:7.4-v3-apache
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_router.rule=Host(`api.${HOST_URL}`)
    environment:
      # Docker image
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_EXTENSION_GD: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_INI_UPLOAD_MAX_FILESIZE: "10M"
      STARTUP_COMMAND_1: "composer install"
      STARTUP_COMMAND_2: "php bin/console doctrine:migrations:migrate -n"
      STARTUP_COMMAND_3: "php bin/console users:create-super-admin"
      # Symfony
      APP_ENV: "dev"
      APP_SECRET: "8d2a5c935d8ef1c0e2b751147382bc75"
      DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE"
      TEST_DATABASE_URL: "mysql://tests:secret@mysql_tests/tests"
      ROOT_PATH: "/var/www/html/"
      MODEL_IMPORT_NAME: "modele_import_utilisateurs.xlsx"
      # CORS
      CORS_ALLOW_ORIGIN: "*"
      # E-mail
      MAILER_URL: "$MAILER_URL"
      MAILER_FROM: "s.gouider@thecodingmachine.com"
      # Super admin
      API_SUPER_ADMIN_FIRST_NAME: "$API_SUPER_ADMIN_FIRST_NAME"
      API_SUPER_ADMIN_LAST_NAME: "$API_SUPER_ADMIN_LAST_NAME"
      API_SUPER_ADMIN_EMAIL: "$API_SUPER_ADMIN_EMAIL"
      API_SUPER_ADMIN_PASSWORD: "$API_SUPER_ADMIN_PASSWORD"
      API_SUPER_ADMIN_PHONE: "$API_SUPER_ADMIN_PHONE"
      # host
      HOST_URL: "$HOST_URL"
      HOST_PROTOCOL: "$HOST_PROTOCOL"
      LINKEDIN_LINK: "$LINKEDIN_LINK"
      SITE_OASYS_LINK: "$SITE_OASYS_LINK"
      TWITTER_LINK: "$TWITTER_LINK"
    volumes:
      - ./src/api:/var/www/html:rw

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - mysql_data:/var/lib/mysqloasys.localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin_router.rule=Host(`db.${HOST_URL}`)
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "$MYSQL_USER"
      PMA_PASSWORD: "$MYSQL_PASSWORD"

  mysql_tests:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "tests"
      MYSQL_USER: "tests"
      MYSQL_PASSWORD: "secret"
    tmpfs:
      - /var/lib/mysql

  mailcatcher:
    image: schickling/mailcatcher
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailcatcher_router.rule=Host(`ml.${HOST_URL}`)
      - traefik.http.routers.mailcatcher_router.service=mailcatcher_service
      - traefik.http.services.mailcatcher_service.loadbalancer.server.port=1080

volumes:

  mysql_data:
    driver: local
