<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Logging\LoggableModel;
use App\Domain\Model\Generated\AbstractFileDescriptor;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FileDescriptor class maps the 'file_descriptors' table in database.
 *
 * @Type
 */
class FileDescriptor extends AbstractFileDescriptor implements LoggableModel
{
}
