<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractMigrationVersion;

/**
 * The MigrationVersion class maps the 'migration_versions' table in database.
 */
class MigrationVersion extends AbstractMigrationVersion
{
}
