<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Exception\InvalidStringValue;
use App\Domain\Model\Generated\AbstractResetPasswordToken;
use Safe\Exceptions\PasswordException;
use TheCodingMachine\GraphQLite\Annotations\Type;
use function Safe\password_hash;
use const PASSWORD_DEFAULT;

/**
 * The ResetPasswordToken class maps the 'reset_password_token' table in database.
 *
 * @Type
 */
class ResetPasswordToken extends AbstractResetPasswordToken
{
    /**
     * @throws InvalidStringValue
     */
    public function setAccessToken(string $accessToken): void
    {
        $property = 'access_token';
        InvalidStringValue::notBlank($accessToken, $property);
        try {
            parent::setAccessToken(password_hash($accessToken, PASSWORD_DEFAULT));
        } catch (PasswordException $e) {
            throw new InvalidStringValue($e->getMessage(), 400, $e);
        }
    }
}
