<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\AbstractUserType;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The UserType class maps the 'users_types' table in database.
 *
 * @Type
 */
class UserType extends AbstractUserType
{
}
