security:
    encoders:
        App\Infrastructure\Security\SerializableUser:
            algorithm: 'auto'
    #    App\Entity\User:
    #        algorithm: auto
    providers:
        custom_user_provider:
            id: App\Infrastructure\Security\UserProvider
        in_memory: { memory: ~ }
        #pdo:
        #    entity:
        #        class: App\Entity\User
        #        property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: custom_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
